name: My First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet to User
        run: echo "Hello there we are Swiss Army"
      - name: Print GoodBye
        run: echo " Oh ! You are Sri Lankan No Entry"


