name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greetings
        run: echo "Hello World" 
        
      - name: Print goodBye
        run: echo "Till we meet Again GoodBye" 
        
      - name: Print Create a New File
        run: touch sahan.txt
        
      - name: Print Adding Content
        run: echo "Hi Sahan How are You" >> sahan.txt

      - name: Print View Content
        run: cat sahan.txt
