name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Greetings
        run: echo "Hello World" 
        
      - name: Print goodBye
        run: echo "Till we meet Again GoodBye" 
        
      - name: Print goodBye
        run: echo "Till we meet Again GoodBye 2 " 
        
      - name: Print Adding Content
        run: echo "Hi Sahan How are You" >> sahan.txt
